---
server:
  update_cache: yes

nginx:
  service_host: "dev-api.dsuapp.ro"
  service_document_root: "/var/www/DSU-reportapp-api/api/public"
  service_host2: "dev-api-admin.dsuapp.ro"
  service_document_root2: "/var/www/DSU-reportapp-api-admin/api-man/public"
  service_admin_email: "lucian.stuparu@civictech.ro"
  renew_ssl_now: "off"
  generate_dhparams: "off"
  certificate_path: "/etc/ssl/certs/dev-api.dsuapp.ro.crt"
  certificate_key_path: "/etc/ssl/private/dev-api.dsuapp.ro.key"
  generate_ssl_now: "on"
  self_signed_certificate:
    - name: "DSU"
      country: "RO"
      state: "Bucharest"
      locality: "Bucharest"
      organization: "DSU"
      organizationalunit: "IT"
      commonname: "dev-api.dsuapp.ro"
      email: "lucian.stuparu@civictech.ro"
  user:
    name: www-data
    group: www-data

php:
  repository: ppa:ondrej/php
  package_cli: php7.1-cli
  package_fpm: php7.1-fpm
  path: /etc/php/7.0
  service_name: php7.1-fpm
  fastcgi_pass: 'unix:/run/php/php7.1-fpm.sock'
  extensions:
    - php7.1-cli
    - php7.1-bcmath
    - php7.1-mbstring
    - php7.1-mcrypt
    - php7.1-intl
    - php7.1-curl
    - php7.1-gd
    - php7.1-zip
    - php7.1-xml
    - php7.1-pgsql

php_config_ini:
  fpm:
    - option: "upload_max_filesize"
      value: "8M"
    - option: "post_max_size"
      value: "8M"
      section: "PHP"
  cli:
    - option: "date.timezone"
      value: "Europe/Bucharest"
      section: "Date"

php_fpm_config_pool:
    - option: "user"
      value: "www-data"
    - option: "group"
      value: "www-data"
    - option: "listen.owner"
      value: "www-data"
    - option: "listen.group"
      value: "www-data"
#    - option: "pm.max_children"
#      value: "25"
#    - option: "pm.start_servers"
#      value: "4"
#    - option: "pm.min_spare_servers"
#      value: "4"
#    - option: "pm.max_spare_servers"
#      value: "6"
