swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  description: API pentru aplicatia de raportare integrata a DSU
  version: 0.0.1
  title: DSU API
  termsOfService: ''
  contact:
    email: tudor.rusu@hotmail.com
  license:
    name: Mozilla Public License 2.0
    url: 'https://www.mozilla.org/en-US/MPL/2.0/'
host: dsu-api.ro
basePath: /
schemes:
  - https

################################################################################
#                                  Paths                                       #
################################################################################


################################################################################
#                                 Definitions                                  #
################################################################################