---
- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name: reload nginx
  service: name=nginx enabled=yes state=reloaded

- name: restart webserver
  service: name=nginx enabled=yes state=restarted

- name: reload webserver
  service: name=nginx enabled=yes state=reloaded
