#!/bin/bash

# Create vagrant log directory
mkdir -p /var/log/vagrant

# Initialize vagrant log file variable
VLOG=/var/log/vagrant/boot.log

# Disable prompt
export DEBIAN_FRONTEND=noninteractive

# Add repository in order to install latest version
#apt-add-repository -y -u ppa:ansible/ansible &>> $VLOG

# Install ansible
#apt-get install -y ansible &>> $VLOG
