---
- name: Local VM Provisioning
  hosts: "local"
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/local.yml
    - vars/local_secrets.yml
  roles:
    - server
    - nginx
    - php        
    - postgres
    - app
